version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi-container
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    command: ["./wait_for_postgres.sh", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]


  # Serviço do banco de dados PostgreSQL
  db:
    image: postgres:13
    container_name: postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Script de inicialização
    ports:
      - "5432:5432"

  # Serviço opcional de Adminer para acesso ao banco
  adminer:
    image: adminer
    container_name: adminer-container
    ports:
      - "8080:8080"
